### ISSUE TITLE
net-p2p/ogmios: Review rc script

### ISSUE THREAD

**Issue by arrowd** [freebsd/freebsd-ports-haskell#74]
- Do we need to create a user for the daemon?
- ~~Why it uses a real cardano-node socket file under jail instead of a public symlink?~~
- Is it OK to have `-o ${logfile}` in the `daemon` call?

**Comment by reqlez** [comment]
Reason uses real socket is because i am mounting the whole socket directory via nullfs, this is why i changed cardano-node to have socket under /socket/ directory instead of jail root.

I think one of the commits has some information about this.

ogmios does not have any other logging configuration as far as i'm aware? But i can look into this. I know cardano-node and cardano-db-sync i configured logging via json file.

**Comment by arrowd** [comment]
> Reason uses real socket is because i am mounting the whole socket directory via nullfs, this is why i changed cardano-node to have socket under /socket/ directory instead of jail root.

Ah, right. And the ogmios itself runs under a jail, so it needs a nullfs mounted into it.

> ogmios does not have any other logging configuration as far as i'm aware? But i can look into this.

The problem with `-o ${logfile}` is that these logs aren't rotated and can grow up to enormous sizes. If there is nothing useful in these logs, it can be removed. On the other hand, if logs are useful, but scarce, they can just be redirected to stdout.

**Comment by reqlez** [comment]
> The problem with `-o ${logfile}` is that these logs aren't rotated and can grow up to enormous sizes. If there is nothing useful in these logs, it can be removed. On the other hand, if logs are useful, but scarce, they can just be redirected to stdout.

Let me review what kind of output there is, and logging options and i will get back to you.

**Comment by arrowd** [comment]
Any progress on this?

**Comment by reqlez** [comment]
> Any progress on this?
oh yea... i completely forgot about this one... checking now

**Comment by reqlez** [comment]
![image](https://user-images.githubusercontent.com/6512602/184198025-aac360cd-a235-40fe-9278-edcb724cebfc.png)
So the logging is useful... however, there is not setting that i can do in config file or anything to redirect logs to something else.

How do you want to handle that ?  Logs are not extremely spammy or anything it seems.

**Comment by arrowd** [comment]
How about cleaning them on the service start so that they wouldn't pile up?

**Comment by reqlez** [comment]
> How about cleaning them on the service start so that they wouldn't pile up?

not a bad idea for now... unless we figure out a rotation later. but clear before the service actually starts since we need start-up logs if things don't work.

I honestly think we should do the same for cardano-node ... if config file is bad, it will output to console and people won't be able to figure out why cardano-node is not starting.
